version: '3.8'
services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5420:5432'
volumes:
  postgres: