version: "3.8"
services:
  db:
    image: postgres:latest
    restart: always # Makes sure the container will always restarts, if it stops for any unexpected reason
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=apassword
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
volumes:
  db:
